### ISSUE TITLE
Request body not shown

### ISSUE THREAD

**Issue by SGrondin** [Mashape/analytics-agent-node#21]
We have a user complaining that he can't see the **request** bodies, he's using the node agent. I also just tried it on staging with HARchiver and I could see the body. He says the response body works, so it's unlikely that he's not doing the right thing.

**Comment by sheppyc** [comment]
Was this me who reported this issue? If so, the analytics node module middleware wasn't added early enough in the request, and was too late. And therefore resolved.

**Comment by sinzone** [comment]
@SGrondin ^
